[package]
name = "tide-bufread"
version = "0.1.0"
authors = ["Jonathan Reyes <j@jreyes.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.7.0"
async-std = "1.5.0"
